services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${DOCKER_PLATFORM}
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/op-ranking-page
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    restart: always

  db:
    image: mysql:5.7
    platform: ${DOCKER_PLATFORM}
    volumes:
      - db_data:/var/lib/mysql
      - ./admin/sql:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=${DB_CHARSET}
      - --collation-server=${DB_COLLATION}
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_CHARSET=${DB_CHARSET}
      - MYSQL_COLLATION=${DB_COLLATION}
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
    name: op-ranking-db-data