services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/op-ranking-page
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=op_ranking
    restart: always

  db:
    image: mysql:5.7
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    volumes:
      - db_data:/var/lib/mysql
      - ./admin/sql:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=op_ranking
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
    name: op-ranking-db-data