name: Deploy to Mac Mini
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAC_MINI_IP }}
        username: ${{ secrets.MAC_MINI_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /Users/yptse123/Documents/op-ranking
          git pull
          
          # Set up PATH for Docker
          export PATH=$PATH:/usr/local/bin:/opt/homebrew/bin
          
          # Check if Docker is available
          if command -v docker >/dev/null 2>&1; then
            echo "Docker found in PATH"
            
            # Configure Docker to use password-less authentication for this session
            export DOCKER_CLI_EXPERIMENTAL=enabled
            mkdir -p ~/.docker
            
            # Create or update Docker config to skip credential helper
            echo '{"credsStore":"", "auths":{"https://index.docker.io/v1/":{}}}' > ~/.docker/config.json
            
            # Try docker compose command (newer Docker versions use 'docker compose')
            if docker compose version >/dev/null 2>&1; then
              echo "Using 'docker compose' command..."
              docker compose down -v || true
              docker volume prune -f || true
              docker compose pull --quiet || true
              docker compose build --no-cache
              docker compose up -d
            # Fall back to docker-compose command
            elif command -v docker-compose >/dev/null 2>&1; then
              echo "Using 'docker-compose' command..."
              docker-compose down -v || true
              docker-volume prune -f || true
              docker-compose pull --quiet || true
              docker-compose build --no-cache
              docker-compose up -d
            else
              echo "ERROR: Neither 'docker compose' nor 'docker-compose' found"
              exit 1
            fi
          else
            echo "ERROR: Docker is not installed or not in PATH"
            echo "Please install Docker Desktop for Mac"
            exit 1
          fi